#pragma once

#include <string>
#include <string_view>

namespace lumina::i18n {

// The object classes Lúmina narrates in the beta (a subset of the 80 COCO
// classes the YOLO11n model knows). Keeping this as an enum (not raw ints) makes
// the pipeline self-documenting and the Spanish labels data-driven (FR-08).
// C++ note (for Java readers): `enum class` is scoped and type-safe, the closest
// C++ equivalent to a Java enum (no implicit conversion to int).
enum class ObjectClass {
    Person,
    Bicycle,
    Car,
    Motorcycle,
    Bus,
    Truck,
    Cat,
    Dog,
    Backpack,
    Chair,
    Couch,
    DiningTable,
    Unknown,  // a class the model knows but we do not narrate
};

// Map a raw COCO class id (the model's `classId`) to our subset.
// Returns ObjectClass::Unknown for anything not in the subset.
[[nodiscard]] ObjectClass fromCocoId(int cocoClassId) noexcept;

// Spanish label for a tracked class (es_MX, INV-042). Returns "" for Unknown.
[[nodiscard]] const char* spanishLabel(ObjectClass objectClass) noexcept;

// Spanish plural for a tracked class (es_MX, INV-042). Returns "" for Unknown.
// Kept explicit rather than generated by a rule because Spanish plurals are not
// rule-based: "camión" -> "camiones" and "autobús" -> "autobuses" drop the accent,
// while "sofá" -> "sofás" keeps it.
[[nodiscard]] const char* spanishPlural(ObjectClass objectClass) noexcept;

// Gendered indefinite article for a class ("un"/"una"), or "" for Unknown.
// Spanish uses the article for a single item ("una persona", "un carro") instead
// of the numeral one.
[[nodiscard]] const char* indefiniteArticle(ObjectClass objectClass) noexcept;

// Spelled-out Spanish cardinal for 2..10, or nullptr outside that range. We never
// emit digits, to avoid relying on the TTS engine's number normalization.
[[nodiscard]] const char* numberWord(int count) noexcept;

// Short Spanish proximity/obstacle alert (FR-02). `veryClose` selects the more
// urgent wording ("cuidado, obstáculo cerca.") over the gentler one
// ("obstáculo cerca."). Returns a stable string literal, never null.
[[nodiscard]] const char* proximityAlertPhrase(bool veryClose) noexcept;

// Spanish greeting for a recognized enrolled person (FR-03): "<nombre> está
// enfrente" (exact approved wording). The name is inserted verbatim because it is
// user-provided enrollment data. Building it here keeps phrase wording out of
// pipeline logic and lets main() pre-warm every enrolled name (INV-051).
[[nodiscard]] std::string greeting(std::string_view name);

}  // namespace lumina::i18n
